import{a as b,S as v,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const S="51708087-f8f02a96469b9e03eb4d8b8de",q="https://pixabay.com/api/",P=15;async function u(s,r){return(await b.get(q,{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:r}})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more");let R=new v(".gallery a");function m(s){const r=s.map(e=>`
    <a class="gallery-item" href="${e.largeImageURL}">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      <div class="info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </a>
  `).join("");f.insertAdjacentHTML("beforeend",r),R.refresh()}function B(){f.innerHTML=""}function y(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function E(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const w=document.querySelector(".form"),$=w.querySelector("[name='search-text']"),A=document.querySelector(".load-more");let c="",i=1,l=0;w.addEventListener("submit",async s=>{s.preventDefault();const r=$.value.trim();if(!r){n.error({message:"Please enter a search term",position:"topRight"});return}c=r,i=1,B(),L(),y();try{const e=await u(c,i);if(l=e.totalHits,e.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),l>e.hits.length&&E()}catch(e){n.error({message:"An error occurred while fetching images",position:"topRight"}),console.error(e)}finally{g()}});A.addEventListener("click",async()=>{i+=1,y();try{const s=await u(c,i);m(s.hits);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*15>=l&&(L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){n.error({message:"An error occurred while fetching images",position:"topRight"}),console.error(s)}finally{g()}});
//# sourceMappingURL=index.js.map
